sudo: required
services:
  - docker

before_install:
  - docker build -t ktadikonda/dockercomplex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ktadikonda/dockercomplex npm run test -- --coverage

after_success:
  - docker build -t ktadikonda/dockercomplex-client ./client
  - docker build -t ktadikonda/dockercomplex-nginx ./nginx
  - docker build -t ktadikonda/dockercomplex-server ./server
  - docker build -t ktadikonda/dockercomplex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ktadikonda/dockercomplex-client
  - docker push ktadikonda/dockercomplex-nginx
  - docker push ktadikonda/dockercomplex-server
  - docker push ktadikonda/dockercomplex-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "DockerComplex"
  env: "DockerComplex-env"
  bucket_name: "elasticbeanstalk-us-east-1-702935569139"
  bucket_path: "DockerComplex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
