sudo: required
services:
  - docker

before_install:
  - docker build -t ktadikonda/dockercomplex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ktadikonda/dockercomplex npm run test -- --coverage

after_success:
  - docker build -t ktadikonda/dockercomplex-client ./client
  - docker build -t ktadikonda/dockercomplex-nginx ./nginx
  - docker build -t ktadikonda/dockercomplex-server ./server
  - docker build -t ktadikonda/dockercomplex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ktadikonda/dockercomplex-client
  - docker push ktadikonda/dockercomplex-nginx
  - docker push ktadikonda/dockercomplex-server
  - docker push ktadikonda/dockercomplex-worker
